### ISSUE TITLE
Incorrect AST resulting from parsing `$a && $b = $c`

### ISSUE THREAD

**Issue by TysonAndre** [Microsoft/tolerant-php-parser#266] opened 2018-11-28 00:16 UTC
tolerant-php-parser is parsing this as `($a && $b) = $c`. It should instead parse this as `$a && ($b = $c)`. ($a && $b) is not a valid target for an assignment, so that shouldn't be created

Using https://github.com/phan/phan/blob/master/internal/dump_fallback_ast.php (prints shorter representation of AST):

I observe the below incorrect AST (I'd expect AssignmentExpression to be the right child node of BinaryExpression)

```
» php internal/dump_fallback_ast.php '<?php $a && $b = $c;'    
Node\SourceFileNode
    statementList: Node\Statement\ExpressionStatement
        expression: Node\Expression\AssignmentExpression
            leftOperand: Node\Expression\BinaryExpression
                leftOperand: Node\Expression\Variable
                    name: Token: VariableName(3): "$a"
                operator: Token: AmpersandAmpersandToken(234): " &&"
                rightOperand: Node\Expression\Variable
                    name: Token: VariableName(3): " $b"
            operator: Token: EqualsToken(238): " ="
            rightOperand: Node\Expression\Variable
                name: Token: VariableName(3): " $c"
        semicolon: Token: SemicolonToken(237): ";"
    endOfFileToken: Token: EndOfFileToken(1): ""
```

This was discovered when investigating https://github.com/phan/phan/issues/2180

**Comment by mattacosta** [comment] 2018-11-28 00:54
Duplicate of #19.

**Closed** 2018-11-28 00:59 UTC
