### ISSUE TITLE
Direct use of curried functions is considered an error

### ISSUE THREAD

**Issue by kilbiller** [Microsoft/tolerant-php-parser#213] opened 2017-11-30 07:33 UTC
Hello,

I was using https://github.com/felixfbecker/php-language-server when I encoutered a bug that seems to come from this project.

Using the result of a curried functions displays the following errors:
- [php] ';' expected.
- [php] ')' expected.

Example code:
```php
$hello = function () {
    return function () {
        return 'hello';
	};
};

$res = $hello()();
```

But it is valid php. (php >= 7 at least, I didn't check for earlier versions)

https://github.com/felixfbecker/php-language-server/issues/542

**Comment by TysonAndre** [comment] 2017-11-30 07:34
This looks like a duplicate of https://github.com/Microsoft/tolerant-php-parser/issues/175

**Comment by kilbiller** [comment] 2017-11-30 07:37
It is!

Sorry I didn't find this issue before reporting.

**Comment by TysonAndre** [comment] 2018-02-16 04:48
This can be closed. The duplicate issue was fixed, and so should this. (Fixed by https://github.com/Microsoft/tolerant-php-parser/pull/223 )

**Closed** 2018-02-16 05:35 UTC
