### ISSUE TITLE
 Add a "vendor" top level namespace

### ISSUE THREAD

**Issue by remicollet** [Microsoft/tolerant-php-parser#35] opened 2017-01-21 13:28 UTC
From http://www.php-fig.org/psr/psr-4/

> The fully qualified class name MUST have a top-level namespace name, also known as a “vendor namespace”.

Ok, you can say "PhpParser" is the vendor... a way to circumvent PSR-4 (as the project SubNamespaceName is not mandatory.. one reason why I dislike this PSR). And PhpParser could be a bit too generic and may create conflict.

Al least, it conflicts with https://packagist.org/packages/nikic/php-parser

Proposal: use Microsoft\PhpParser

I understand this is only doable as part of a new major version, because of BC break.

**Comment by mattacosta** [comment] 2017-01-21 13:31
Duplicate of #22

**Comment by mousetraps** [comment] 2017-01-22 19:39
Thanks @remicollet! We'll take care of it - the API is caveated well-enough that it should be fine to take in immediately without worrying about a version change.

**Closed by mousetraps** 2017-01-22 19:39 UTC
Labels: duplicate
